# Generated by Django 4.2 on 2023-05-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_pet_brand_pet_country_name_delete_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='person_name',
        ),
        migrations.AddField(
            model_name='person',
            name='country_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='app.country'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, null=True)),
                ('varient', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('person_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='app.person')),
            ],
        ),
    ]
