# Generated by Django 4.2 on 2023-05-05 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_pet_country_name_remove_pet_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='app.vehicle'),
        ),
    ]
